apps/dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.BaseURL.as_view(), name='baseurl'),
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^general/$', views.GeneralSettings.as_view(), name='general'),
    url(r'^sites/$', views.Sites.as_view(), name='sites'),
    url(r'^sites/add/$', views.SitesAdd.as_view(), name='sitesadd'),
    url(r'^sites/change/(?P<sitepk>.*)/$', views.SitesChange.as_view(), name='siteschange'),
    url(r'^sitetypes/$', views.SiteTypes.as_view(), name='sitetypes'),
    url(r'^sitetypes/add/$', views.SiteTypesAdd.as_view(), name='sitetypesadd'),
    url(r'^sitetypes/change/(?P<sitetypepk>.*)/$', views.SiteTypesChange.as_view(), name='sitetypeschange'),
    url(r'^templates/$', views.Templates.as_view(), name='templates'),
    url(r'^templates/add/$', views.TemplatesAdd.as_view(), name='templatesadd'),
    url(r'^pagelayouts/$', views.PageLayouts.as_view(), name='pagelayouts'),
    url(r'^pagelayouts/add/$', views.PageLayoutsAdd.as_view(), name='pagelayoutsadd'),
    url(r'^pagelayouts/change/(?P<pagelayoutpk>.*)/$', views.PageLayoutsChange.as_view(), name='pagelayoutschange'),
    url(r'^sitepublishers/$', views.SitePublishers.as_view(), name='sitepublishers'),
    url(r'^sitepublishers/add/$', views.SitePublishersAdd.as_view(), name='sitepublishersadd'),
    url(r'^sitepublishers/change/(?P<sitepublisherpk>.*)/$', views.SitePublishersChange.as_view(), name='sitepublisherschange'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from ajax_select import urls as ajax_select_urls
import apps.thirdparty.django_saml2_auth.django_saml2_auth.views
from django.contrib.auth.views import logout
from apps.common.classes import CustomSearchView, CustomSearchForm
from haystack.views import SearchView
from django.http import HttpResponse
from socket import gethostname
import os

app_name = 'config'
urlpatterns = [
url(r'^saml_login/', include('apps.thirdparty.django_saml2_auth.django_saml2_auth.urls')),
url(r'^accounts/login/$', apps.thirdparty.django_saml2_auth.django_saml2_auth.views.signin),
url(r'^accounts/logout/$', logout,{'next_page': 'https://adfs.slcschools.org/adfs/ls/?wa=wsignout1.0&wreply=https://www.slcschools.org/'})
]

# Check system health
def check_health():
    hostname = gethostname()
    failed = []
    if not os.path.isfile('/srv/lb'):
        failed.append('/srv/lb file is missing')
    critical_services = [
        'nginx',
        'varnish',
        'redis',
        'gunicorn_www_slcschools_org',
        'php-fpm',
        'haproxy',
    ]
    for service in critical_services:
        status = os.system('/usr/bin/systemctl is-active {} --quiet'.format(service))
        if status:
            failed.append('{0} service has status {1}'.format(service, status))
    if failed:
        return 503, 'Offline', hostname, '<br>'.join(failed)
    return 200, 'Online', hostname, '<br>'.join(failed)

# Server Name and Status
def servername(request):
    status, state, hostname, failed = check_health()
    response = HttpResponse('Server {0}: {1}<br><br>{2}'.format(
        state,
        hostname,
        failed,
    ), status=status)
    response['Cache-Control'] = 'no-cache, max-age=0, must-revalidate'
    return response


urlpatterns += [
    url(r'^server/$', servername, name='servername'),
]

# Dashboard App

urlpatterns += [
    url(r'^manage/', include('apps.dashboard.urls')),
]

# Search Results
urlpatterns += [
    url(r'^search/results/', CustomSearchView.as_view(), name="haystack_search"),
]

# Media Library
urlpatterns += [
    url(r'^medialibrary/', include('apps.medialibrary.urls')),
]

admin.site.site_header = 'Salt Lake City School District'
admin.site.index_title = ('Salt Lake City School District')
admin.site.site_title = ('Salt Lake City School District')

urlpatterns += [
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^jet/', include('jet.urls', 'jet')),
    # url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^backend/', admin.site.urls),
]

if settings.DEBUG and settings.ENVIRONMENT_MODE == 'development':
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

# Pages App Should be last since it matches all urls at the end.
urlpatterns += [
  url(r'', include('apps.pages.urls')),
]

apps/cmstemplates/views.py
from django.shortcuts import render

# Create your views here.

apps/dashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic.base import RedirectView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms.formsets import formset_factory
from django.forms.models import modelformset_factory
from django.contrib import messages
from django.urls import reverse
from django.apps import apps
from apps.objects.models import User
from apps.dashboard.forms import (
    GeneralSettingsForm,
    SitesAddForm,
    SitesChangeForm,
    SiteTypesAddForm,
    SiteTypesChangeForm,
    SiteTypesRequiredPagesForm,
    TemplatesAddForm,
    PageLayoutsAddForm,
    PageLayoutsChangeForm,
    SitePublishersAddForm,
    SitePublishersChangeForm,
)
from apps.dashboard.models import (
    GeneralSettings as GeneralSettingsModel,
    SiteType as SiteTypeModel,
    SiteTypeRequiredPage as SiteTypeRequiredPageModel,
    Template as TemplateModel,
    PageLayout as PageLayoutsModel,
    SitePublisher as SitePublisherModel,
)


def add_sites_context(self, context):
    Alias = apps.get_model('multisite', 'alias')
    context['host'] = self.request.META['HTTP_HOST']
    env = context['host'].split('.')[0]
    if '-test' in env:
        context['sites'] = (
            Alias
            .objects
            .filter(domain__icontains='-test')
            .order_by('domain')
        )
    elif '-dev' in env:
        context['sites'] = (
            Alias
            .objects
            .filter(domain__icontains='-dev')
            .order_by('domain')
        )
    else:
        context['sites'] = (
            Alias
            .objects
            .filter(is_canonical=True)
            .order_by('domain')
        )
    return context


def add_sitetypes_context(self, context):
    context['sitetypes'] = SiteTypeModel.objects.all().order_by('title')
    return context


def add_templates_context(self, context):
    context['templates'] = TemplateModel.objects.all().order_by('title')
    return context


def add_pagelayouts_context(self, context):
    context['pagelayouts'] = PageLayoutsModel.objects.all().order_by('title')
    return context


def add_sitepublishers_context(self, context):
    context['sitepublishers'] = SitePublisherModel.objects.filter(site=self.request.site).order_by('account')
    return context


def add_general_settings_form(self, context):
    instance = GeneralSettingsModel.objects.get(site=self.request.site)
    if self.request.POST:
        context['generalsettingsform'] = GeneralSettingsForm(
            data=self.request.POST,
            instance=instance,
        )
    else:
        context['generalsettingsform'] = GeneralSettingsForm(instance=instance)
    return context


def add_sitesadd_form(self, context):
    if self.request.POST:
        context['sitesaddform'] = SitesAddForm(
            data=self.request.POST,
        )
    else:
        context['sitesaddform'] = SitesAddForm()
    return context


def add_siteschange_form(self, context):
    try:
        instance = GeneralSettingsModel.objects.get(pk=self.kwargs['sitepk'])
    except GeneralSettingsModel.DoesNotExist:
        raise Exception('Site Does Not Exist')
    if self.request.POST:
        context['siteschangeform'] = SitesChangeForm(
            instance=instance,
            data=self.request.POST,
        )
    else:
        context['siteschangeform'] = SitesChangeForm(
            instance=instance,
        )
    return context


def add_sitetypesadd_form(self, context):
    if self.request.POST:
        context['sitetypesaddform'] = SiteTypesAddForm(
            data=self.request.POST,
        )
    else:
        context['sitetypesaddform'] = SiteTypesAddForm()
    return context


def add_sitetypeschange_form(self, context):
    try:
        instance = SiteTypeModel.objects.get(pk=self.kwargs['sitetypepk'])
    except SiteTypeModel.DoesNotExist:
        raise Exception('Site Type Does Not Exist')
    RequiredPagesFormSet = modelformset_factory(
        SiteTypeRequiredPageModel,
        form=SiteTypesRequiredPagesForm,
    )
    if self.request.POST:
        context['sitetypeschangeform'] = SiteTypesChangeForm(
            instance=instance,
            data=self.request.POST,
        )
        context['requiredpagesformset'] = RequiredPagesFormSet(data=self.request.POST)
    else:
        context['sitetypeschangeform'] = SiteTypesChangeForm(
            instance=instance,
        )
        context['requiredpagesformset'] = RequiredPagesFormSet(queryset=SiteTypeRequiredPageModel.objects.filter(sitetype=instance))
        for form in context['requiredpagesformset']:
            form.fields['pagelayout'].queryset = instance.dashboard_pagelayout_allowed_sitetypes.all().order_by('title')
            form.fields['parent'].queryset = instance.dashboard_sitetyperequiredpage_sitetype.all().order_by('title')
    return context


def add_templatesadd_form(self, context):
    if self.request.POST:
        context['templatesaddform'] = TemplatesAddForm(
            data=self.request.POST,
        )
    else:
        context['templatesaddform'] = TemplatesAddForm()
    return context


def add_pagelayoutsadd_form(self, context):
    if self.request.POST:
        context['pagelayoutsaddform'] = PageLayoutsAddForm(
            data=self.request.POST,
        )
    else:
        context['pagelayoutsaddform'] = PageLayoutsAddForm()
    return context


def add_pagelayoutschange_form(self, context):
    try:
        instance = PageLayoutsModel.objects.get(pk=self.kwargs['pagelayoutpk'])
    except PageLayoutsModel.DoesNotExist:
        raise Exception('Page Layout Does Not Exist')
    if self.request.POST:
        context['pagelayoutschangeform'] = PageLayoutsChangeForm(
            instance=instance,
            data=self.request.POST,
        )
    else:
        context['pagelayoutschangeform'] = PageLayoutsChangeForm(
            instance=instance,
        )
    return context


def add_sitepublishersadd_form(self, context):
    if self.request.POST:
        context['sitepublishersaddform'] = SitePublishersAddForm(
            data=self.request.POST,
        )
    else:
        context['sitepublishersaddform'] = SitePublishersAddForm()
    return context


def add_sitepublisherschange_form(self, context):
    try:
        instance = SitePublisherModel.objects.get(pk=self.kwargs['sitepublisherpk'])
    except SitePublisherModel.DoesNotExist:
        raise Exception('Site Publisher Does Not Exist')
    if self.request.POST:
        context['sitepublisherschangeform'] = SitePublishersChangeForm(
            instance=instance,
            data=self.request.POST,
        )
    else:
        context['sitepublisherschangeform'] = SitePublishersChangeForm(
            instance=instance,
        )
    return context


class SAMLLoginRequiredMixin(LoginRequiredMixin):
    login_url = '/accounts/login/?next=/'


class BaseURL(SAMLLoginRequiredMixin, RedirectView):

    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        return reverse('dashboard:dashboard')


class Dashboard(SAMLLoginRequiredMixin, TemplateView):

    template_name = 'cmstemplates/dashboard/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = add_sites_context(self, context)
        return context


class GeneralSettings(SAMLLoginRequiredMixin, TemplateView):

    template_name = 'cmstemplates/dashboard/general.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        if context['generalsettingsform'].is_valid():
            user = User.objects.get(pk=request.user.pk)
            post = context['generalsettingsform'].save(commit=False)
            if not post.create_user:
                post.create_user = user
            post.update_user = user
            post.save()
            messages.success(
                request,
                'Settings updated successfully')
        return redirect('dashboard:general')

    def get(self, request, *args, **kwargs):
        model, created = GeneralSettingsModel.objects.get_or_create(
            site=request.site
        )
        if created:
            model.create_user = request.user
            model.update_user = request.user
            model.save()
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = add_sites_context(self, context)
        context = add_general_settings_form(self, context)
        return context


class Sites(SAMLLoginRequiredMixin, TemplateView):

    template_name = 'cmstemplates/dashboard/sites.html'

    def get(self, request, *args, **kwargs):
        if request.site.domain != 'websites.slcschools.org':
            return BaseURL.as_view()(self.request)
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = add_sites_context(self, context)
        return context


class SitesAdd(SAMLLoginRequiredMixin, TemplateView):

    template_name = 'cmstemplates/dashboard/sitesadd.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        if context['sitesaddform'].is_valid():
            user = User.objects.get(pk=request.user.pk)
            post = context['sitesaddform'].save(commit=False)
            if not post.create_user:
                post.create_user = user
            post.update_user = user
            post.save()
            messages.success(
                request,
                'Site added successfully')
        return redirect('dashboard:sites')

    def get(self, request, *args, **kwargs):
        if request.site.domain != 'websites.slcschools.org':

apps/cmstemplates/templates/cmstemplates/dashboard/dashboard.html
{% extends 'cmstemplates/dashboard/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block maincontent %}
<div class="col s12">
  <div class="card-panel">
  abc
  </div>
</div>
<div class="col s12 m4">
  <div class="card-panel">
  abc
  </div>
</div>
<div class="col s12 m4">
  <div class="card-panel">
  abc
  </div>
</div>
<div class="col s12 m4">
  <div class="card-panel">
  abc
  </div>
</div>
{% endblock %}

apps/cmstemplates/templates/cmstemplates/dashboard/pagelayouts.html
{% extends 'cmstemplates/dashboard/base.html' %}

{% block title %}Page Layouts{% endblock %}

{% block maincontent %}
<div class="col s12">
  <div class="card-panel">
    <div class="row">
      <h1 class="col s12">Page Layouts</h1>
    </div>
    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Layouts</th>
            <th class="rowaction"><span class="sr-only">Edit</span><th>
          </tr>
        </thead>
        <tbody>
          {% for layout in pagelayouts %}
          <tr>
            <td><a href="{% url 'dashboard:pagelayoutschange' pagelayoutpk=layout.pk %}">{{ layout.title }}</a><br>{{ layout.namespace }}</td>
            <td class="rowaction">
              <a href="{% url 'dashboard:pagelayoutschange' pagelayoutpk=layout.pk %}">
                <span class="sr-only">Edit {{ layout.title }}</span>
                <span class="no-sr md-settings" aria-hidden="True"></span>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'dashboard:pagelayoutsadd' %}" class="btn-floating btn-large waves-effect waves-light" style="position: fixed; bottom: 15px; right: 15px;"><span class="md-plus"></span></a>
    </div>
  </div>
</div>
{% endblock %}

apps/cmstemplates/templates/cmstemplates/dashboard/pagelayoutsadd.html
{% extends 'cmstemplates/dashboard/base.html' %}

{% block title %}Add Page Layout{% endblock %}

{% block maincontent %}
<div class="col s12">
  <div class="card-panel">
  	<div class="row">
  	  <h1 class="col s12">Add Page Layout</h1>
    </div>
    <div class="row">
	  	<form class="col s12 focus" action="{% url 'dashboard:pagelayoutsadd' %}" method="post">
		    {% csrf_token %}
		    <div class="input-field col s12">
		      <span class="md-filedocument prefix" aria-hidden="true"></span>
		      {{ pagelayoutsaddform.title.errors }}
		      {{ pagelayoutsaddform.title }}
		      <label for="{{ pagelayoutsaddform.title.id_for_label}}">Page Layout Name</label>
		    </div>
		    <div class="input-field col s12">
		      <span class="md-code-tags prefix" aria-hidden="true"></span>
		      {{ pagelayoutsaddform.namespace.errors }}
		      {{ pagelayoutsaddform.namespace }}
		      <label for="{{ pagelayoutsaddform.namespace.id_for_label}}">HTML File Name</label>
		    </div>
		    <div class="input-field col s12">
		      <span class="material-icons prefix" aria-hidden="true"></span>
		      <button type="submit" class="waves-effect waves-green btn">
		        <span class="sr-only">Submit</span>
		        <span class="no-sr" aria-hidden="true">Submit</span>
		      </button>
		    </div>
		  </form>
		</div>
  </div>
</div>
{% endblock %}

apps/cmstemplates/templates/cmstemplates/dashboard/pagelayoutschange.html
{% extends 'cmstemplates/dashboard/base.html' %}

{% block title %}Change Page Layout{% endblock %}

{% block maincontent %}
<div class="col s12">
  <div class="card-panel">
  	<div class="row">
  	  <h1 class="col s12">Change Page Layout</h1>
    </div>
    <div class="row">
	  	<form class="col s12 focus" action="" method="post">
		    {% csrf_token %}
		    <div class="input-field col s12">
		      <span class="md-filedocument prefix" aria-hidden="true"></span>
		      {{ pagelayoutschangeform.title.errors }}
		      {{ pagelayoutschangeform.title }}
		      <label for="{{ pagelayoutschangeform.title.id_for_label}}">Page Layout Name</label>
		    </div>
		    <div class="input-field col s12">
		      <span class="md-code-tags prefix" aria-hidden="true"></span>
		      {{ pagelayoutschangeform.namespace.errors }}
		      {{ pagelayoutschangeform.namespace }}
		      <label for="{{ pagelayoutschangeform.namespace.id_for_label}}">HTML File Name</label>
		    </div>
		    <div class="input-field col s12">
		      <span class="md-code-tags prefix" aria-hidden="true"></span>
		      {{ pagelayoutschangeform.allowed_sitetypes.errors }}
		      {{ pagelayoutschangeform.allowed_sitetypes }}
		      <label for="{{ pagelayoutschangeform.allowed_sitetypes.id_for_label}}">Allowed Site Types:</label>
		    </div>
		    <div class="input-field col s12">
		      <span class="material-icons prefix" aria-hidden="true"></span>
		      <button type="submit" class="waves-effect waves-green btn">
		        <span class="sr-only">Submit</span>
		        <span class="no-sr" aria-hidden="true">Submit</span>
		      </button>
		    </div>
		  </form>
		</div>
  </div>
</div>
{% endblock %}

apps/cmstemplates/templates/cmstemplates/dashboard/sitepublishersadd.html
{% extends 'cmstemplates/dashboard/base.html' %}

{% block title %}Add Site Publisher{% endblock %}

{% block maincontent %}
<div class="col s12">
  <div class="card-panel">
  	<div class="row">
  	  <h1 class="col s12">Add Site Publisher</h1>
    </div>
    <div class="row">
	  	<form class="col s12 focus" action="{% url 'dashboard:sitepublishersadd' %}" method="post">
		    {% csrf_token %}
		    {{ sitepublishersaddform.media }}
		    <div class="input-field col s12">
		      <span class="md-person prefix" aria-hidden="true"></span>
		      {{ sitepublishersaddform.account.errors }}
		      {{ sitepublishersaddform.account }}
		      <label class="active" for="{{ sitepublishersaddform.account.id_for_label}}">Publisher</label>
		    </div>
		    <div class="input-field col s12">
		      <span class="material-icons prefix" aria-hidden="true"></span>
		      <button type="submit" class="waves-effect waves-green btn">
		        <span class="sr-only">Submit</span>
		        <span class="no-sr" aria-hidden="true">Submit</span>
		      </button>
		    </div>
		  </form>
		</div>
  </div>
</div>
{% endblock %}

apps/cmstemplates/templates/cmstemplates/dashboard/sites.html
{% extends 'cmstemplates/dashboard/base.html' %}

{% block title %}Sites{% endblock %}

{% block maincontent %}
<div class="col s12">
  <div class="card-panel">
    <div class="row">
      <h1 class="col s12">Sites</h1>
    </div>
    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Site</th>
            <th class="rowaction"><span class="sr-only">Edit</span><th>
          </tr>
        </thead>
        <tbody>
          {% for site in sites %}
          <tr>
            <td><a href="{% url 'dashboard:siteschange' sitepk=site.site.dashboard_general_site.pk %}">{{ site.site.dashboard_general_site.title }}</a><br>{{ site.domain }}</td>
            <td class="rowaction">
              <a href="{% url 'dashboard:siteschange' sitepk=site.site.dashboard_general_site.pk %}">
                <span class="sr-only">Edit {{ site.site.dashboard_general_site.title }}</span>
                <span class="no-sr md-settings" aria-hidden="True"></span>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'dashboard:sitesadd' %}" class="btn-floating btn-large waves-effect waves-light" style="position: fixed; bottom: 15px; right: 15px;"><span class="md-plus"></span></a>
    </div>
  </div>
</div>
{% endblock %}

apps/cmstemplates/templates/cmstemplates/dashboard/sitetypes.html
{% extends 'cmstemplates/dashboard/base.html' %}

{% block title %}Site Types{% endblock %}

{% block maincontent %}
<div class="col s12">
  <div class="card-panel">
    <div class="row">
      <h1 class="col s12">Site Types</h1>
    </div>
    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Site Type</th>
            <th class="rowaction"><span class="sr-only">Edit</span><th>
          </tr>
        </thead>
        <tbody>
          {% for sitetype in sitetypes %}
          <tr>
            <td><a href="{% url 'dashboard:sitetypeschange' sitetypepk=sitetype.pk %}">{{ sitetype.title }}</a></td>
            <td class="rowaction">
              <a href="{% url 'dashboard:sitetypeschange' sitetypepk=sitetype.pk %}">
                <span class="sr-only">Edit {{ sitetype.title }}</span>
                <span class="no-sr md-settings" aria-hidden="True"></span>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'dashboard:sitetypesadd' %}" class="btn-floating btn-large waves-effect waves-light" style="position: fixed; bottom: 15px; right: 15px;"><span class="md-plus"></span></a>
    </div>
  </div>
</div>
{% endblock %}

apps/cmstemplates/templates/cmstemplates/dashboard/sitetypesadd.html
{% extends 'cmstemplates/dashboard/base.html' %}

{% block title %}Add Site Type{% endblock %}

{% block maincontent %}
<div class="col s12">
  <div class="card-panel">
  	<div class="row">
  	  <h1 class="col s12">Add Site Type</h1>
    </div>
    <div class="row">
	  	<form class="col s12 focus" action="{% url 'dashboard:sitetypesadd' %}" method="post">
		    {% csrf_token %}
		    <div class="input-field col s12">
		      <span class="md-filedocument prefix" aria-hidden="true"></span>
		      {{ sitetypesaddform.title.errors }}
		      {{ sitetypesaddform.title }}
		      <label for="{{ sitetypesaddform.title.id_for_label}}">Site Type Name</label>
		    </div>
		    <div class="input-field col s12">
		      <span class="material-icons prefix" aria-hidden="true"></span>
		      <button type="submit" class="waves-effect waves-green btn">
		        <span class="sr-only">Submit</span>
		        <span class="no-sr" aria-hidden="true">Submit</span>
		      </button>
		    </div>
		  </form>
		</div>
  </div>
</div>
{% endblock %}

apps/cmstemplates/templates/cmstemplates/dashboard/templates.html
{% extends 'cmstemplates/dashboard/base.html' %}

{% block title %}Templates{% endblock %}

{% block maincontent %}
<div class="col s12">
  <div class="card-panel">
    <div class="row">
      <h1 class="col s12">Templates</h1>
    </div>
    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Template</th>
            <th class="rowaction"><span class="sr-only">Edit</span><th>
          </tr>
        </thead>
        <tbody>
          {% for template in templates %}
          <tr>
            <td><a href="/manage/dashboard/">{{ template.title }}</a><br>{{ template.namespace }}</td>
            <td class="rowaction">
              <a href="/manage/dashboard/">
                <span class="sr-only">Edit {{ template.title }}</span>
                <span class="no-sr md-settings" aria-hidden="True"></span>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'dashboard:templatesadd' %}" class="btn-floating btn-large waves-effect waves-light" style="position: fixed; bottom: 15px; right: 15px;"><span class="md-plus"></span></a>
    </div>
  </div>
</div>
{% endblock %}

apps/cmstemplates/templates/cmstemplates/dashboard/templatesadd.html
{% extends 'cmstemplates/dashboard/base.html' %}

{% block title %}Add Template{% endblock %}

{% block maincontent %}
<div class="col s12">
  <div class="card-panel">
  	<div class="row">
  	  <h1 class="col s12">Add Template</h1>
    </div>
    <div class="row">
	  	<form class="col s12 focus" action="{% url 'dashboard:templatesadd' %}" method="post">
		    {% csrf_token %}
		    <div class="input-field col s12">
		      <span class="md-filedocument prefix" aria-hidden="true"></span>
		      {{ templatesaddform.title.errors }}
		      {{ templatesaddform.title }}
		      <label for="{{ templatesaddform.title.id_for_label}}">Template Name</label>
		    </div>
		    <div class="input-field col s12">
		      <span class="md-code-tags prefix" aria-hidden="true"></span>
		      {{ templatesaddform.namespace.errors }}
		      {{ templatesaddform.namespace }}
		      <label for="{{ templatesaddform.namespace.id_for_label}}">Namespace</label>
		    </div>
		    <div class="input-field col s12">
		      <span class="material-icons prefix" aria-hidden="true"></span>
		      <button type="submit" class="waves-effect waves-green btn">
		        <span class="sr-only">Submit</span>
		        <span class="no-sr" aria-hidden="true">Submit</span>
		      </button>
		    </div>
		  </form>
		</div>
  </div>
</div>
{% endblock %}